name: create aws infra lab1
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
jobs:
  create_plan:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v4
      - name: set-up terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: setup aws-cli
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GIT_TOKEN }}
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::985539789378:role/Oidc-admin
          aws-region: ap-south-1
          run: | 
           aws sts get-caller-identity
      - name: initialize, format and plan
        run: |
          terraform init
          terraform fmt
          terraform plan -out myplan
      - name: apply_plan
        run: terraform apply myplan
